name: Deploy to Cloudflare Pages for preview on commit to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install wasm-pack
        run: npm install -g wasm-pack

      - name: Build WASM
        run: wasm-pack build

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./dist --project-name=typer-concierge --branch=preview
